%YAML:1.0
---
aruco_bc_dict: ARUCO_MIP_36h12
aruco_bc_nmarkers: 6
aruco_bc_mInfoType: 0
aruco_bc_markers:
   - { id:54, corners:[ [ -500., -250., 0. ], [ 0., -250., 0. ], [ 0.,
       -750., 0. ], [ -500., -750., 0. ] ] }
   - { id:55, corners:[ [ 100., -250., 0. ], [ 600., -250., 0. ], [ 600.,
       -750., 0. ], [ 100., -750., 0. ] ] }
   - { id:56, corners:[ [ -500., 350., 0. ], [ 0., 350., 0. ], [ 0.,
       -150., 0. ], [ -500., -150., 0. ] ] }
   - { id:57, corners:[ [ 100., 350., 0. ], [ 600., 350., 0. ], [ 600.,
       -150., 0. ], [ 100., -150., 0. ] ] }
   - { id:58, corners:[ [ -500., 950., 0. ], [ 0., 950., 0. ], [ 0.,
       450., 0. ], [ -500., 450., 0. ] ] }
   - { id:59, corners:[ [ 100., 950., 0. ], [ 600., 950., 0. ], [ 600.,
       450., 0. ], [ 100., 450., 0. ] ] }
